config/routes.rb
PerformanceManage::Application.routes.draw do
  root "users#show"
  resource :user, controller: :users, only: [:show]
  resources :users, only: [:index, :edit, :update, :new, :create]
  resources :performances do
    collection do
      get :unapprove, action: :unapprove
    end
    member do
      patch :approve, action: :approve
    end
  end
  resources :projects, only: [:index, :show, :create, :new, :edit, :update]
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :performances
  belongs_to :group, class_name: "ProjectGroup", foreign_key: "group_id"
  has_many :project_members
  has_many :users, through: :project_members
  has_many :partner_costs

  accepts_nested_attributes_for :users

  validates :name,        presence: true
  validates :start_date,  presence: true
  validates :end_date,    presence: true
  validates :order,       presence: true
  validates :project_code,presence: true
  validates :group_id,    presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :project_find, only: [ :show, :edit, :update ]
  before_action :assign_users, only: [ :new, :edit, :update ]
  before_action :admin_only!,  only: [ :new, :create, :edit, :update ]
  before_action :reject_partner!

  def index
    @projects = current_user.projects
  end

  def show
    @project_users = project_users(@project)
  end

  def new
    @project_form = ProjectForm.new
  end

  def create
    @users = assign_users
    @project = Project.new
    @project_form = ProjectForm.new(project_params)
    @project.assign_attributes(@project_form.project_attributes)
    @project.users << @project_form.users_attributes
    if @project_form.shape_user_ids.present? && @project.save
      flash[:success] = "プロジェクトを新規作成しました．"
      redirect_to user_path
    else
      flash.now[:danger] = "プロジェクトの新規作成に失敗しました．"
      render action: :new
    end
  end

  def edit
    @project_form = ProjectForm.new.assign_project_attributes(@project)
  end

  def update
    @project_form = ProjectForm.new(project_params)
    @project.assign_attributes(@project_form.project_attributes)
    @project.users << @project_form.users_attributes(@project)
    if @project.save
      # TODO: ProjectMemberテーブルを更新する処理を書く．
      flash[:success] = "プロジェクト情報を変更しました．"
      redirect_to projects_path
    else
      flash[:danger] = "プロジェクト情報の変更に失敗しました．"
      redirect_to edit_project_path(@project)
    end
  end

private
  def project_params
    params.require(:project_form).permit( :name,
                                          :start_date,
                                          :end_date,
                                          :order,
                                          :project_code,
                                          :group_id,
                                          member_ids: [])
  end

  # 引数のプロジェクトに属するユーザの配列を生成する．
  def project_users(project)
    users = []
    project.users.each do |user|
      users << [user.name, user.id]
    end
    users
  end

  # プロジェクト新規作成・編集に使うユーザの配列を生成する．
  def assign_users
    users = User.all.order(:id)
    @users = [].tap do |array|
      users.each do |user|
        array.push([user.name, user.id])
      end
    end
  end

  def project_find
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<% provide(:title, "プロジェクト編集") %>
<%= form_for(@project_form, :url => {:controller => :projects, action: :update}, method: "patch" ) do |f| %>
  <table class="table">
    <tr>
      <td><%= f.label "プロジェクト名" %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label "期間" %></td>
      <td>
        <%= f.date_field :start_date, :value => @project_form.start_date.strftime("%Y-%m-%d") %>
        <%= f.date_field :end_date, :value => @project_form.end_date.strftime("%Y-%m-%d") %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "受注先" %></td>
      <td>
        <%= f.text_field :order %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "プロジェクトコード" %></td>
      <td>
        <%= f.text_field :project_code %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "種別" %></td>
      <td>
        <%= f.select :group_id, ProjectGroup.all.map{|group| [group.name, group.id] }%>
      </td>
    </tr>
    <tr>
      <td>メンバー</td>
      <td>
        <%= f.select :member_ids, @users, {}, { :multiple => true, :size => 20, :selected => @project_form.member_ids }%>
      </td>
    </tr>
  </table>
  <%= f.submit "変更", class: "btn btn-primary"%>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, "プロジェクト一覧") %>
<table class="table table-striped">
  <tr>
    <th>プロジェクト名</th><th>期間</th><th>状態</th><th> </th>
  </tr>
<% @projects.each do |project| %>
  <tr>
    <td>
      <%= project.name %>
    </td>
    <td>
      <%= project.start_date %> ~ <%= project.end_date %>
    </td>
    <td>
      <% if project.end_date.strftime < Date.today.strftime %>
        <span class="label label-default">Close</span>
      <% else %>
        <span class="label label-primary">Open</span>
      <% end %>
    </td>
    <td>
      <%= link_to "詳細", project_path(project) %>
      <%= link_to("編集", edit_project_path(project)) if current_user.admin? %>
    </td>
  </tr>
<% end %>
</table>

app/views/projects/new.html.erb
<% provide(:title, "プロジェクト新規作成") %>
<%= form_for(ProjectForm.new, :url => {:controller => :projects, action: :create}, method: "post" ) do |f| %>
  <table class="table">
    <tr>
      <td><%= f.label "プロジェクト名" %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label "期間" %></td>
      <td>
        <%= f.date_field :start_date, :value => Date.today.strftime("%Y-%m-%d") %> 〜
        <%= f.date_field :end_date, :value => Date.today.next_month.strftime("%Y-%m-%d") %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "受注先" %></td>
      <td>
        <%= f.text_field :order %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "プロジェクトコード" %></td>
      <td>
        <%= f.text_field :project_code %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "種別" %></td>
      <td>
        <%= f.select :group_id, ProjectGroup.all.map{|group| [group.name, group.id] }%>
      </td>
    </tr>
    <tr>
      <td>メンバー</td>
      <td>
        <%= f.select :member_ids, @users, {}, { :multiple => true, :size => 10 }%>
      </td>
    </tr>
  </table>
  <%= f.submit "プロジェクト新規作成", class: "btn btn-primary"%>
<% end %>

app/views/projects/show.html.erb
<% provide(:title, "プロジェクト詳細") %>

<table class="table">
  <tr>
    <td>プロジェクト名</td><td><%= @project.name %></td>
  </tr>
  <tr>
    <td>期間</td><td><%= @project.start_date %> ~ <%= @project.end_date %></td>
  </tr>
  <tr>
    <td>状態</td>
    <td>
      <% if @project.end_date.strftime < Date.today.strftime %>
        <span class="label label-default">Close</span>
      <% else %>
        <span class="label label-primary">Open</span>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>受注先</td><td><%= @project.order %></td>
  </tr>
  <tr>
    <td>プロジェクトコード</td><td><%= @project.project_code %></td>
  </tr>
  <tr>
    <td>メンバー</td>
    <td>
      <%= select :member, :index, @project_users, {}, {:multiple => false, :size => @project_users.length+1} %>
    </td>
  </tr>
</table>