config/routes.rb
PerformanceManage::Application.routes.draw do
  root "users#show"
  resource :user, controller: :users, only: [:show]
  resources :users, only: [:index, :edit, :update, :new, :create]
  resources :performances do
    collection do
      get :unapprove, action: :unapprove
    end
    member do
      patch :approve, action: :approve
    end
  end
  resources :projects, only: [:index, :show, :create, :new, :edit, :update]
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :user,      :class_name => "User",  :foreign_key => "user_id"
  belongs_to :approver,  :class_name => "User",  :foreign_key => "approver_id"
  belongs_to :project

  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :content,     presence: true
  validates :project_id,  presence: true
  validates :user_id,     presence:true
  validates :approver_id, presence: true, if: :approve?

  validate  :end_time_check
  validate  :approver_is_admin?, if: :approve?

  def end_time_check
    if self.end_time <= self.start_time
      errors.add(:end_time, "日付を正しく入力してください．")
    end
  end

  def approver_is_admin?
    unless User.find(self.approver_id).admin?
      errors.add(:approver, "承認者は管理者のみです．")
    end
  end

  def approve?
    self.permission == true
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :signed_in?
  before_action :admin_only!, only: [:unapprove, :approve]
  before_action :not_allow_change!, only: [:edit, :update, :destroy]
  before_action :person_limit!, only: [:edit, :destroy]


  def index
    @performances = Performance.where(user_id: current_user).order(created_at: :desc)
  end

  def edit
    @performance = Performance.find(params[:id])
    @performance_form = PerformanceForm.new.assign_performance_attributs(@performance)
  end

  def update
    @performance_form = PerformanceForm.new(performance_params.merge(user_id: current_user.id))
    @performance = Performance.find(params[:id])
    @performance.assign_attributes(@performance_form.performance_attributes)
    if @performance.save
      flash[:success] = "稼働実績の変更に成功しました．"
      redirect_to performances_path
    else
      flash[:danger] = "稼働実績の変更に失敗しました．"
      redirect_to edit_performance_path(params[:id])
    end
  end

  def unapprove
    @performances = Performance.where(permission: false).order(created_at: :desc)
  end

  def show
    @performance = Performance.find(params[:id])
    unless @performance.user == current_user || current_user.admin?
      flash[:danger] = "管理者以外は他ユーザの稼働実績は見れません．"
      redirect_to performances_path
    end
  end

  def approve
    if Performance.find(params[:id]).update(permission: true, approver_id: current_user.id)
      flash[:success] = "承認しました．"
      redirect_to unapprove_performances_path
    else
      flash.now[:danger] = "承認に失敗しました．"
      redirect_to unapprove_performances_path
    end
  end

  def create
    @user = User.find_by(remember_token: User.encrypt(cookies[:remember_token]))
    @performance_form = PerformanceForm.new(performance_params.merge(user_id: current_user.id))
    if @performance_form.save
      redirect_to user_path, :flash => { :success => "稼働実績の登録に成功しました．" }
    else
      flash.now[:danger] = "稼働実績の登録に失敗しました．"
      @projects = Project.all
      render template: 'users/show'
    end
  end

  def destroy
    Performance.find(params[:id]).destroy
    flash[:success] = "稼働実績を削除しました．"
    redirect_to performances_path
  end

private
    def performance_params
      params.require(:performance_form).permit(:start_time,
                                          :end_time,
                                          :content,
                                          :permission,
                                          :project_id)
    end

    def not_allow_change!
      @performance = Performance.find(params[:id])
      if @performance.permission?
        flash[:danger] = "承認済みのため，変更が許可されていません．"
        redirect_to performances_path
      end
    end

    def person_limit!
      unless Performance.find(params[:id]).user == current_user
        flash[:danger] = "稼働実績作成者以外は変更できません"
        redirect_to performances_path
      end
    end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<%= form_for(performance_form, :url => { :controller => :performances, action: action}, method: method) do |f| %>
  <table class="table">
    <tr>
      <td><%= f.label "プロジェクト" %></td>
      <td><%= f.select :project_id, current_user.projects.map{|p| [p.name, p.id]} %></td>
    </tr>
    <tr>
      <td><%= f.label "開始日時" %></td>
      <td>
        <%= f.datetime_local_field :start_time, :value => performance_form.generate_datetime(:start_time)  %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "終了日時" %></td>
      <td>
        <%= f.datetime_local_field :end_time, :value => performance_form.generate_datetime(:end_time) %>
      </td>
    </tr>
    <tr>
      <td><%= f.label "作業内容" %></td>
      <td><%= f.text_area :content, :size => "50x10" %></td>
    </tr>
  </table>
  <%= f.submit "稼働登録", class: "btn btn-primary"%>
<% end %>

app/views/performances/_new.html.erb
<% provide(:title, "稼働実績新規作成") %>
<%= render partial: 'performances/form', locals: {performance_form: PerformanceForm.new, action: :create, method: :post} %>

app/views/performances/edit.html.erb
<% provide(:title, "稼働実績編集") %>
<%= render partial: 'form', locals: {performance_form: @performance_form, action: :update, method: :patch} %>

app/views/performances/index.html.erb
<% provide(:title, "稼働実績一覧") %>
<table class="table table-striped">
  <tr>
    <th>ユーザ名</th><th>プロジェクト名</th><th>作業時間</th><th>承認状況</th><th>承認者</th><th>    </th>
  </tr>
<% @performances.each do |performance| %>
  <tr>
    <td>
      <%= performance.user.name %>
    </td>
    <td>
      <%= performance.project.name %>
    </td>
    <td>
      <%= performance.start_time %> ~ <%= performance.end_time %>
    </td>
    <% unless performance.permission %>
      <td colspan="2" align=center>
        <div class="label label-success">未承認</div>
      </td>
      <td>
        <%= link_to "詳細", performance_path(performance), class: "btn btn-info"%>
        <%= link_to "変更", edit_performance_path(performance), class: "btn btn-primary" %>
        <%= link_to "削除", performance, method: :delete, data: { confirm: "稼働実績を削除しますか?" }, class: "btn btn-danger" %>
      </td>
      <% else %>
      <td>
        <div class="label label-warning">承認済み</div>
      </td>
      <td>
        <%= performance.approver.name %>
      </td>
      <td>
        <%= link_to "詳細", performance_path(performance), class: "btn btn-info"%>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/performances/index_unapprove.html.erb
<h1>未承認稼働実績一覧</h1>
<% @performances.each do |performance| %>
  <li>
    ユーザ名: <%= performance.user.name %>    作業時間: <%= performance.start_time %> ~ <%= performance.end_time %>
    <%= link_to "詳細", performance_path(performance) %>
    <%= link_to "承認", "#" %>
  </li>
<% end %>

app/views/performances/show.html.erb
<% provide(:title, "稼働実績詳細") %>

<table class="table unapprove_show">
  <tr>
    <td>ユーザ名</td><td><%= @performance.user.name %></td>
  </tr>
  <tr>
    <td>プロジェクト名</td><td><%= @performance.project.name %></td>
  </tr>
  <tr>
    <td>作業時間</td><td><%= @performance.start_time %> ~ <%= @performance.end_time %></td>
  </tr>
  <tr>
    <td>作業内容</td><td id="unapprove_content"><%= sanitize(simple_format(@performance.content), :tags => %w(br p)) %></td>
  </tr>
</table>

<% if current_user.admin? && !@performance.permission %>
  <%= link_to "承認", approve_performance_path(@performance), method: "patch", class: "btn btn-primary" %>
<% end %>

app/views/performances/unapprove.html.erb
<% provide(:title, "未承認稼働実績一覧") %>
<h1>未承認稼働実績一覧</h1>

<table class="table table-striped">
  <tr>
    <th>ユーザ名</th><th>プロジェクト名</th><th>作業時間</th><th>    </th>
  </tr>
<% @performances.each do |performance| %>
  <tr>
    <td>
      <%= performance.user.name %>
    </td>
    <td>
      <%= performance.project.name %>
    </td>
    <td>
      <%= performance.start_time %> ~ <%= performance.end_time %>
    </td>
    <td>
      <%= link_to "詳細", performance_path(performance), class: "btn btn-info" %>
      <%= link_to "承認", approve_performance_path(performance), method: "patch", class: "btn btn-primary" %>
    </td>
  </tr>
<% end %>
</table>