config/routes.rb
PerformanceManage::Application.routes.draw do
  root "users#show"
  resource :user, controller: :users, only: [:show]
  resources :users, only: [:index, :edit, :update, :new, :create]
  resources :performances do
    collection do
      get :unapprove, action: :unapprove
    end
    member do
      patch :approve, action: :approve
    end
  end
  resources :projects, only: [:index, :show, :create, :new, :edit, :update]
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><a href="http://www.cuon.co.jp/" target="_blank">About</a></li>
      <li><a href="http://news.railstutorial.jp/" target="_blank">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "稼働実績管理", user_path, id: 'logo' %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <% unless current_user.partner? %>
              <li><%= link_to "プロジェクト", projects_path %></li>
            <% end %>
            <li><%= link_to "稼働実績一覧", performances_path %></li>
            <li><%= link_to "サインアウト", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "サインイン", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if signed_in? %>
      <div class="row user-info">
        <p>ユーザ名:<%= current_user.name %></p>
        <p>ユーザID:<%= current_user.email %></p>
        <p>権限: <%= current_user.authority.text %></p>
      </div>
      <% if current_user.admin? %>
      <div class="row">
        <ul class="buttons-for-admin">
          <li><%= link_to 'ユーザ新規作成', new_user_path, class: "btn btn-primary"%></li>
          <li><%= link_to 'ユーザ一覧', users_path, class: "btn btn-primary"%></li>
          <li><%= link_to 'プロジェクト作成', new_project_path, class: "btn btn-primary" %></li>
          <li>
            <%= link_to unapprove_performances_path, class: "btn btn-primary" do %>
              未承認稼働実績一覧<span class="badge"><%= Performance.where(:permission => false).count %></span>
            <% end %>
          </li>
        </ul>
      </div>
      <% end %>
      <% flash.each do |key, value|  %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>